language: rust
env:
  global:
    - secure: gGXnsjG6nClIp7muPqLXw9Fsc94TnJ43j7+eVAp3EwTtNwq5/lKw95HR9sYawcsDTAVTTfm83lZ1UNdZbM0VHzQjoPTjdathBWBgM2YjpZzoRrHyJtdEtUAr0d3WQo++yjrb5sUZTccoirPyJQ3HkKY45k9PYoQeGlYAnj84FkI=
after_script:
  - cargo doc --verbose
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
